.xcodesamplecode.plist
Same contents as my merged PRs into [swift-numerics](https://github.com/apple/swift-numerics/pull/34), [swift-crypto](https://github.com/apple/swift-crypto/pull/11), [swift-argument-parser](https://github.com/apple/swift-argument-parser/pull/12) and [library-preview](https://github.com/apple/swift-standard-library-preview/pull/1) (establishing precedence 😎), giving proper markdown rendering inside Xcode.
Reading of markdown becomes easier. Extra important in Swift packages, where the `README` is the first file opened by Xcode when opening said package.
Just adding the `.xcodesamplecode.plist` file (to the root).
As seen in [Apple's ARKit demo (inside `/ARKitExample.xcodeproj/` directory)](https://developer.apple.com/sample-code/wwdc/2017/PlacingObjects.zip)
This effectively **_disables …
=> Give markdown rendering of README inside Xcode

Sources/Lifecycle/Lifecycle.swift
It seems to me that the comments of shutdownSignal and installBacktrace were inverted, I apologize in advance if I misunderstood something.
=> Update ServiceLifecycle.Configuration comments

README.md
The README.md only listed 3 of the 4 Configuration options and did not mention the logging option.  This is important because using swift-service-lifecycle in an existing app which already uses logging can impact that logging unless this configuration item is set.
Added logging option to the configuration discussion.
Placed it first, which is the same as the argument order for ServiceLifecycle.Configuration.
=> Updated README.md to include logger configuration option

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ServiceLifecycleTests+XCTest.swift, Tests/LifecycleTests/ServiceLifecycleTests.swift, docker/Dockerfile, docker/docker-compose.1804.50.yaml, docker/docker-compose.1804.52.yaml, docker/docker-compose.1804.53.yaml
motivation: fix startAndWait to work as advertised
changes:
* extract shutdown setup to a func and call it from both start and startAndWait
* add test
* fix api doc
=> setup shutdown hooks on ServiceLifecycle::startAndWait

Sources/LifecycleNIOCompat/Bridge.swift
Added some NIO friendly syntactic sugar, based on this comment: https://github.com/swift-server/swift-aws-lambda-runtime/pull/141#discussion_r463877586
Is this something we want to follow through?
=> Add some NIO sugar to ServiceLifecycle.start()

Package.swift
The less requirements a project has the better. Currently `swift-server-lifecycle` requires that macOS is at least at version 10.12.
Since the mentioned requirement is not needed at all, it can be removed.
Less SwiftPM pain. Easier to integrate for downstream repos, without adding new requirements.
=> Remove unused macOS(.v10_12) platform requirement

docker/docker-compose.1804.53.yaml
motivation: Swift 5.3 was released, use if for CI
changes: update docker setup to use the release version of 5.3
=>  Swift 5.3 was released, use if for CI

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
motivation: allow libraries that want to expose the lifecycle so that downstream code could register additional items to do so regardless of the lifecycle backend
changes: abstract registration function into a protocol and conform ComponentLifecycle and ServiceLifecycle to it
=> abstract registration function into a protocol

Sources/Lifecycle/Lifecycle.swift, Sources/LifecycleNIOCompat/Bridge.swift, Tests/LifecycleTests/ComponentLifecycleTests+XCTest.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
motivation: address shutdown for tasks which allocate resources on construction. before this change, only tasks that have been started are shutdown, this creates an issue when the resources are allocated on construction since the item may not get started at all (for example due to error in earlier task) and thus will never be shutdown and the resources will leak.
changes: add semantics to request shutdown even if not started, and assume this se semantics when registering with `start: .none` or with `registerShutdown`
=> add semantics for stopping tasks that have no start handler

.xcodesamplecode.plist, Sources/Lifecycle/Lifecycle.swift
Motivation:
Some servers want to support customised handling of signals except for simply shutting down.
Added support for USR1/USR2 signal traps for (#64) - extended trap() signature with one more optional argument to allow for signal handler to be run multiple times with usage like this:
```
let alrmDispatchSourceSignal = ServiceLifecycle.trap(signal: ServiceLifecycle.Signal.USR1, handler: { signal in
print("signal \(signal)")
}, cancelAfterTrap: false)```
Existing usage of .trap() is unaffected.
Possibly additional signals (HUP?) should be added too.
Changes:
Added USR1/USR2 to Signal struct to allow for trapping them.
Changed .trap() signature to allow for signal handlers to be run multiple times without reregistration.
=> Add support for HUP, USR1, USR2 signals

Package.swift, Sources/CLifecycleHelpers/CLifecycleAtomics.c, Sources/CLifecycleHelpers/include/CLifecycleAtomics.h, Sources/Lifecycle/Atomics.swift, Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ServiceLifecycleTests+XCTest.swift, Tests/LifecycleTests/ServiceLifecycleTests.swift, docker/docker-compose.1804.50.yaml, scripts/soundness.sh
motivation: application frameworks thae use ServiceLifecycle may need to expose their internal lifecycle so they can be also composed into larger systems
changes:
* expose ServiceLifecycle::underlying
* make sure backtrace installer is only called once per process
* add swift-atomics dependency
* make min swift version 5.1 to match new swift-atomics dependency
=> expose the internal lifecycle for composition

README.md, Sources/Lifecycle/Lifecycle.swift, Sources/LifecycleNIOCompat/Bridge.swift, Tests/LifecycleTests/ComponentLifecycleTests+XCTest.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
motivation: allow lifecycle handlers to have the library manage the state for them so they do not need to do that manually
changes:
* introduce LifecycleStartHandler and LifecycleShutdownHandler which can handle state on behalf of the lifecycle item
* add registerStateful function to regsiter stateful handlers
* add tests
=> add support for stateful handler

.xcodesamplecode.plist, Sources/Lifecycle/Lifecycle.swift
Motivation:
Small code cleanup, reusing LifecycleTask as the shutdown hooks are
to be installed just at the beginning of that chain of events anyway.
Discussed previously in context of https://github.com/swift-server/swift-service-lifecycle/pull/87
Modifications:
Moved signal handler installation to LifecycleTask instead of direct calls.
Result:
Slightly simpler code.
=> Install signal handlers as LifecycleTasks

Sources/Lifecycle/Lifecycle.swift
motivation: start handlers should not actually be part of the initialization process, as it breaks composition between ServiceLifecycles
=> Revert "Install signal handlers as LifecycleTasks"

Sources/Lifecycle/Atomics.swift
Since `swift-atomics` is not 1.0 we should ensure that we don't leak its API. For this reason we should import it as `@_implementationOnly`.
=> Import Atomics @_implementationOnly

Sources/Lifecycle/Lifecycle.swift
motivation: there is no need to explose the underlying component lifecycle, since there are better composition solutions
changets: make ServiceLifecycle::underlying private (again)
=> make the underlying component lifecycle private again

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ComponentLifecycleTests+XCTest.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
motivation: startup/shutdown metrics are important for real-life services, for example spike in start metrics indicates a crash-loop
changes:
* add start and shutdown counters to ComponentLifecycle
* add start and shutdown timers to report duration of startup and shutdown operations
=> add lifecycle metrics

Sources/Lifecycle/Lifecycle.swift
**Motivation:**
Since Swift Log 1.3.0, log handlers can include the source of a particular message,
rendering the [Lifecycle] prefix unnecessary.
**Modifications:**
Removed the [Lifecycle] prefix from all log messages by removing the underlying
log helper and calling out to the Logger itself.
**Result:**
Log messages written by a log handler which includes the location won't log "Lifecycle" twice.
**Related:**
- [Logging (#135): "add source for log messages"](https://github.com/apple/swift-log/pull/135)
- [Logging (#187): "use #fileID for Swift 5.3+"](https://github.com/apple/swift-log/pull/187)
- [Logging (#189): "Include source in StreamLogHandler output"](https://github.com/apple/swift-log/pull/189)
=> Remove [Lifecycle] prefix from log messages

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ComponentLifecycleTests+XCTest.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
motivation: async/await is coming in 5.5, take first steps to support it
changes:
* introduce handler initializers that takes async functions (@escaping () async throws -> Void, @escaping () async throws -> State)
* add tests
=> add handlers that support async functions

Sources/Lifecycle/Lifecycle.swift
motivation: `detach` was replaced with `Task` and `Task.detached`
changes: use `Task {}` instead of `detach {}`
=> adjust to updated concurrency API

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ServiceLifecycleTests+XCTest.swift, Tests/LifecycleTests/ServiceLifecycleTests.swift, docker/Dockerfile
motivation: repeatedly calling shutdown in linux was broken due to multiple calls to singal() which work on darwin but not linux
changes:
* conditionalize the call to signal
* add test
=> fix repeated shutdown issue on linux

docker/Dockerfile
motivation: jazzy no longer works on older version of ubuntu as ruby is too old
changes: update docker to only install jazzy on latest ubuntu versions
=> only install jazzy on latest ubuntu versions

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ComponentLifecycleTests+XCTest.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
motivation: more reliable shutdown in edge cases where lifecycle never gets started
changes: when shutting down an idle lifecycle, try to shutdown any tasks that have shutdownIfNotStarted set to true
=> shutdown any task that have shutdownIfNotStarted set to true when shutting down a never-started-lifecycle

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ComponentLifecycleTests+XCTest.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
motivation: improve confusing behavior
changes:
* change startTask to return an array of started tasks instead of an index
* only shutdown successfully started tasks or ones that have explicitly set shutdownIfNotStarted to true
* add and adjust tests
=> when shutdownIfNotStarted is set to false, dont shutdown items that failed to start

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift
This may be misguided, see comments in #110
=> Switch up compiler directives for concurrency

docker/docker-compose.2004.55.yaml
motivation: 5.5 release is available
changes: update docker CI setup to use the release version of 5.5
=> Use release version of 5.5 in CI

Sources/Lifecycle/Lifecycle.swift
Adds Swift Concurrency Availability to macOS 10.15, iOS 13, tvOS 13, and watchOS 6.
_(Shamelessly copying from https://github.com/apple/swift-nio/pull/2004 @PSchmiedmayer)_
With the support for Swift Concurrency coming to macOS 10.15, iOS 13, tvOS 13, and watchOS 6 with Xcode 13.2, the Swift Concurrency features should be available when compiling for these targets using Xcode 13.2.
Change the `@available` annotations to macOS 10.15, iOS 13, tvOS 13, and watchOS 6.
The Swift Concurrency features are marked with `@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)` and can therefore be used on macOS 10.15, iOS 13, tvOS 13, and watchOS 6.
=> Adds Swift Concurrency Availability to macOS 10.15, iOS 13, tvOS 13, and watchOS 6

Sources/Lifecycle/Lifecycle.swift, Sources/Lifecycle/Locks.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift, Tests/LifecycleTests/ServiceLifecycleTests+XCTest.swift, Tests/LifecycleTests/ServiceLifecycleTests.swift
motivation: allow easier testing of shutdown hooks
changes:
* introduce ServiceLifecycle.removeTrap which removes a trap
* call ServiceLifecycle.removeTrap when setting up the shutdown hook
* make the shutdown hook cleanup into a lifecycle task to ensure correct ordering
* add tests
* improve logging
rdar://89552798
=> shutdown() should cancel the signal handlers installed by start()

Sources/Lifecycle/Lifecycle.swift, Tests/LifecycleTests/ComponentLifecycleTests+XCTest.swift, Tests/LifecycleTests/ComponentLifecycleTests.swift, docker/docker-compose.yaml
motivation: sometimes a task needs to be de-registered since the task was manually shutdown outside the lifecycle scope
changes:
* registration APIs now return a registration key which can be used as a cancellation token
* add API to de-register a task
* refactor state to use a registery instead of array of tasks
* add tests
=> add the ability to de-register a task

Sources/ServiceLifecycle/ServiceGroup.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift
The current naming of `shutdownGracefully()` on the `ServiceGroup` caused some confusion since callers had to `await` the call due the `ServiceGroup` being an `actor`. This lead users to believe that the method waited until the graceful shutdown was completed; however, the method only triggered the shutdown and exited.
This PR renames `ServiceGroup/shutdownGracefully()` to `ServiceGroup/triggerGracefulShtudown()`.
Less confusion around the behaviour of triggering a graceful shutdown on the `ServiceGroup`.
=> Rename `shutdownGracefully` to `triggerGracefulShutdown` on the `ServiceGroup`

Sources/UnixSignals/UnixSignal.swift, Tests/UnixSignalsTests/UnixSignalTests.swift
Some applications want to react to `SIGQUIT` which is similar to `SIGINT` but normally maps to a different key `C-\`.
This PR adds support for `SIGQUIT` in the `UnixSignal`s module.
Support for `SIGQUIT`.
=> Add support for `SIGQUIT`

Sources/ServiceLifecycle/Docs.docc/How to adopt ServiceLifecycle in applications.md, Sources/ServiceLifecycle/Docs.docc/How to adopt ServiceLifecycle in libraries.md, Sources/ServiceLifecycle/GracefulShutdown.swift, Sources/ServiceLifecycle/ServiceGroup.swift, Sources/ServiceLifecycle/ServiceGroupConfiguration.swift, Sources/UnixSignals/UnixSignalsSequence.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift, Tests/ServiceLifecycleTests/XCTest+Async.swift
Currently the `ServiceGroup` cancels the whole group when a service returns or throws. This is fine for most server applications but it doesn't work for CLI tools since they mostly want to use the group to orchestrate the services as long as the user command is handled and then return cleanly from the group. Furthermore, even on server setups one might want to customize the behavior of what happens when a service returns/throws e.g. one might want to shutdown the group after their HTTP server throws so that a telemetry service flushes out all the remaining data.
This PR does a few things:
1. It creates a new `ServiceConfiguration` and `TerminationBehavior` in the `ServiceGroupConfiguration`. Those can be used to declare the services that are run and what happens when the service returns …
=> Add support for `return/ThrowBehavior` of services

Sources/ServiceLifecycle/ServiceGroupConfiguration.swift
To avoid colliding with logging keys of adopters we should prefix our default metadata logging keys.
This PR prefixes our default logging keys with `sl-`.
=> Prefix default logging keys

Sources/ServiceLifecycle/ServiceGroup.swift
Libraries shouldn't log above debug levels.
=> Only log at debug levels

Sources/ServiceLifecycle/ServiceGroup.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift
Propagate the service error when we shutdown the group after the service threw.
=> Propagate service error when gracefully shutting down

Sources/ServiceLifecycle/ServiceGroup.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift
When a service threw during graceful shutdown but had its behaviour set to `gracefulShutdown` itself then we were not rethrowing the error.
This PR makes sure that the first service that throws an error which doesn't have its `failureTerminationBehavior` to `.ignore` gets rethrown by the `ServiceGroup`.
=> Propagate service error during graceful shutdown

Sources/ServiceLifecycle/ServiceGroup.swift
Right now creating a `ServiceGroup` always requires creating a `ServiceGroupConfiguration`. This is making the barrier to use the group higher than needed for the 99% use-case.
This PR adds a new init on the `ServiceGroup` that takes an array of services, graceful shutdown & cancellation signals and the logger.
Easier use of the service group for the 99% use-case.
=> Add convenience init to the group

.swiftformat, NOTICE.txt, Package.swift, Sources/ServiceLifecycle/AsyncCancelOnGracefulShutdownSequence.swift, Sources/_AsyncMergeSequence/Locking.swift, Sources/_AsyncMergeSequence/Merge/AsyncMerge2Sequence.swift, Sources/_AsyncMergeSequence/Merge/MergeStateMachine.swift, Sources/_AsyncMergeSequence/Merge/MergeStorage.swift, Sources/_AsyncMergeSequence/Rethrow.swift, Tests/ServiceLifecycleTests/AsyncCancelOnGracefulShutdownSequenceTests.swift
We are about to tag a `2.0.0` and cannot depend on any non major package.
This vendors in `swift-async-algorithms` so that we can use the `AsyncMergeSequence`. In the future, once `swift-async-algorithms` is `1.0.0` itself we can swap back.
No more non-major dependency.
=> Vendor `swift-async-algorithms`

Sources/ServiceLifecycle/AsyncGracefulShutdownSequence.swift, Sources/ServiceLifecycle/CancellationWaiter.swift, Sources/ServiceLifecycle/GracefulShutdown.swift, Sources/ServiceLifecycle/ServiceGroup.swift, Tests/ServiceLifecycleTests/GracefulShutdownTests.swift
Sometimes, it's useful to wait for graceful shutdown to happen before resuming execution on a task.
This can be of particular interest when we don't have anything to do in a Service's `run` method but want to make sure some cleanup happens on graceful shutdown.
In this scenario, we can achieve this by calling `await gracefulShutdown()` in `run()`, followed by whatever cleanup we must do.
This PR adds a new `gracefulShutdown()` function to the `GracefulShutdown` suite. 
A new `gracefulShutdown()` method in the `GracefulShutdown` suite.
=> Add async gracefulShutdown function to wait on graceful shutdown trigger

Sources/UnixSignals/UnixSignal.swift, Tests/UnixSignalsTests/UnixSignalTests.swift
`SIGWINCH` is sent to applications when the window resizes. This is useful to observe for terminal applications to reformat the logging one resize.
This PR adds support for `SIGWINCH` in `UnixSignal`s.
=> Add support for `SIGWINCH`

Sources/ServiceLifecycle/ServiceGroup.swift, Sources/ServiceLifecycle/ServiceGroupConfiguration.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift
The service group is often running multiple services and orchestrates shutdown for them. We have seen that sometimes some services never shutdown nor do they respond to task cancellation properly. This can become quite problematic when the whole application is waiting for a service to cancel and otherwise appears to be healthy but in reality can't serve any traffic.
This PR adds a new configuration to escalate both graceful shutdown and cancellation. The escalation order is graceful shutdown -> task cancellation -> `fatalError`. The `fatalError` acts a last resort to make sure applications are never stuck.
=> Add a configurable escalation behaviour

Sources/ServiceLifecycle/ServiceGroup.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift
After calling `shutdownGracefully` in our `ServiceGroup` we know that one of two things happened:
1. We got an error so something went wrong
2. We got no error so all services finished
In the 2. case, there might still be a few child tasks in the task group e.g. the graceful shutdown timeout task. We are currently still iterating the remaining child task results which might lead into unexpected fatal errors.
This PR makes sure that after we have successfully shutdown we are stopping iterating the child task results.
No more unexpected fatal errors.
=> Make sure we return after gracefully shutdown

Sources/ServiceLifecycle/ServiceGroup.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift
This should fix the remaining issues raised in https://github.com/swift-server/swift-service-lifecycle/pull/166. The problem here was that if a service finished/threw out of order then we were wrongly treating this as if the service that we are currently shutting down finished.
This PR ensures that we use the same `services` array during the graceful shutdown to nil out services that have finished. This way we correctly keep track of any service that finished. Additionally, there was a separate bug where we started to shutdown the next service to early if another service threw and had the termination behaviour of `shutdownGracefully`.
No more incorrect shutdown orderings.
=> Fix logic issues during graceful shutdown

Sources/ServiceLifecycle/ServiceGroup.swift, Tests/ServiceLifecycleTests/ServiceGroupTests.swift
It is possible to nest a `ServiceGroup` inside another `ServiceGroup` however we were missing the conformance to `Service` on the group.
This PR adds the conformance to `Service` to `ServiceGroup`.
=> Conform `ServiceGroup` to `Service`

Sources/ServiceLifecycle/GracefulShutdown.swift, Tests/ServiceLifecycleTests/GracefulShutdownTests.swift
Execute an operation with a graceful shutdown or task cancellation handler that’s immediately invoked if the current task is shutting down gracefully or has been cancelled.
=> Add `withTaskCancellationOrGracefulShutdownHandler`

Sources/ServiceLifecycle/AsyncGracefulShutdownSequence.swift, Sources/ServiceLifecycle/CancellationWaiter.swift, Sources/ServiceLifecycle/GracefulShutdown.swift, Tests/ServiceLifecycleTests/GracefulShutdownTests.swift
Currently `cancelOnGracefulShutdown` hangs forever, if cancellation is not immediately but returns a eventually successful result (test case 1: `testCancelOnGracefulShutdownSurvivesCancellation`).
If the Cancellation leads to another error than `CancellationError`, this error is currently not propagated to the user (test case 2: `testCancelOnGracefulShutdownSurvivesErrorThrown`).
- `AsyncGracefulShutdownSequence` should never throw as this hides the real errors otherwise
- `CancellationWaiter` should never throw as this hides the real errors otherwise
- Adjustments in `cancelOnGracefulShutdown`
- `cancelOnGracefulShutdown` works as expected
=> `cancelOnGracefulShutdown` hangs, if cancellation is not immediately

Sources/ServiceLifecycle/GracefulShutdown.swift, Tests/ServiceLifecycleTests/GracefulShutdownTests.swift
Issue: https://github.com/swift-server/swift-service-lifecycle/issues/179
`cancelOnGracefulShutdown` has no code paths that return a `nil` value.
=> Global cancelOnGracefulShutdown returns non nil value

Sources/ConcurrencyHelpers/Lock.swift, Sources/UnixSignals/UnixSignal.swift, Sources/UnixSignals/UnixSignalsSequence.swift, Tests/UnixSignalsTests/UnixSignalTests.swift
When building for Linux, we would like to be able to build this package on top of Musl, as well as the usual Glibc.
Conditionally import `Musl` when present, just like we do for `Glibc`.
Can compile against Musl.
=> Support compiling against Musl

Sources/ServiceLifecycle/GracefulShutdown.swift
Motivation:
Deprecation with rename fixit has been seen to cause compiler crashes in 5.x compiler versions.
Modifications:
Deprecate with message for 5.x compilers.
Result:
Compilation without failure in all scenarios
=> Stop using renamed pattern which can cause compiler crash

Sources/ConcurrencyHelpers/Lock.swift
Motivation:
The 'unsafeDowncast' can cause a miscompile leading to unexpected runtime behaviour.
Modifications:
- Use 'as!' instead
Result:
No miscompiles on 5.10
=> Change 'unsafeDowncast' to 'as!'

README.md, Sources/ServiceLifecycle/Docs.docc/How to adopt ServiceLifecycle in applications.md, Sources/ServiceLifecycle/ServiceGroup.swift, Sources/ServiceLifecycle/ServiceGroupConfiguration.swift
Hello! :wave: This PR contains a few changes, notably:
- Updating the ``README.md`` to use the new initializer instead of the deprecated one.
- Add a ``renamed`` to the deprecated initializer.
- Updating the docs to use the simpler initializer.
- Make the ``logging`` parameter on the initializers optional, the motivation for this is in cases the user don't or can't do logging, they don't have to construct a logger and bootstrap the logging system with ``SwiftLogNoOpLogHandler``, so this code:
```swift
LoggingSystem.bootstrap(SwiftLogNoOpLogHandler.init)
let serviceGroup = ServiceGroup(
services: [service],
cancellationSignals: [.sigint],
logger: .init(label: "")
)
```
becomes
```swift
let serviceGroup = ServiceGroup(
services: [service],
cancellationSignals: [.sigint]
)
```
and it also …
=> Make logging optional and update docs

Sources/UnixSignals/UnixSignal.swift
I'm using swift-service-lifecycle's UnixSignal in a text UI library, and needed SIGCONT. It's probably not super relevant in the service use case, but it looks like UnixSignal is the best way to handle signals, service or not, and I don't know if there's a downside to the library supporting it?
=> UnixSignal: Add SIGCONT

Sources/ServiceLifecycle/GracefulShutdown.swift
Currently, if compiler >= 6 then there are 2 implementations. One is deprecated and one is not.
But if compiler is < 6 then there is only one implementation, which is deprecated. I think this was by mistake.
=> Remove deprecation of withGracefulShutdownHandler if compiler < 6

Sources/ConcurrencyHelpers/Lock.swift, Sources/UnixSignals/UnixSignal.swift, Sources/UnixSignals/UnixSignalsSequence.swift, Tests/UnixSignalsTests/UnixSignalTests.swift
I don't expect us to run CI against this until that's more formally supported, but this would greatly help adoption of server-focused packages on Android
=> Import the Android module if available, since glibc and musl are unavailable on Android

Package.swift, Sources/ServiceLifecycle/AsyncCancelOnGracefulShutdownSequence.swift, Sources/ServiceLifecycle/AsyncGracefulShutdownSequence.swift, Sources/ServiceLifecycle/CancellationWaiter.swift, Sources/ServiceLifecycle/GracefulShutdown.swift, Sources/ServiceLifecycle/Service.swift, Sources/ServiceLifecycle/ServiceGroup.swift, Sources/ServiceLifecycle/ServiceGroupConfiguration.swift, Sources/ServiceLifecycleTestKit/GracefulShutdown.swift, Sources/UnixSignals/UnixSignalsSequence.swift, Tests/ServiceLifecycleTests/GracefulShutdownTests.swift
Motivation:
Adding or raising the deployment platforms in the package manifest is a SemVer major breaking change as consumers must also add or raise their deployment platforms. This is a known limitation of SwiftPM.
Unforunately this means that it's very difficult for non-leaf packages to adopt packages which declare their platforms in the manifest. Doing so puts the brakes on adoption and ecosystem growth. For 'core' packages like this one availability constraints should be expressed on declarations rather than in the manifest.
Modifications:
- Remove platforms from the package manifest
- Add availability annotations to types which require it
Result:
This package can be more widely adopted
=> Remove platforms from manifest

Sources/ServiceLifecycle/Docs.docc/LoggingConfiguration.md, Sources/ServiceLifecycle/Docs.docc/ServiceConfiguration.md, Sources/ServiceLifecycle/Docs.docc/ServiceGroup.md, Sources/ServiceLifecycle/Docs.docc/ServiceGroupConfiguration.md, Sources/ServiceLifecycle/Docs.docc/index.md, Sources/ServiceLifecycle/GracefulShutdown.swift, Sources/ServiceLifecycle/ServiceGroup.swift, Sources/ServiceLifecycle/ServiceGroupConfiguration.swift
A little bit of docs cleanup - adding abstracts for deprecated methods and curating them (organizing them) to the bottom of the relevant lists.
=> adding abstracts and organization to methods
